# ~~~~~ GENERAL ~~~~~ #

# QoL
set -g escape-time 0
set -g repeat-time 1000
set -g history-limit 10000

# VI mode
set-window-option -g mode-keys vi

# Mouse mode
set-window-option -g mouse on

# Start window index at 1
set -g base-index 1

# Start pane index at 1
set -g pane-base-index 1

# Re-number windows when one is closed
set -g renumber-windows on


# ~~~~~ BINDINGS ~~~~~ #

# Re-set prefix
set-option -g prefix 'C-a'
bind-key 'C-a' send-prefix
unbind-key C-b

# Reload config
bind-key r source-file ~/.tmux.conf \; display "Fresh tmux config !"

# Use Alt-{h,j,k,l} keys to switch panes
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v

# ~~~~~ STATUS BAR ~~~~~ #
SURFACE="#181818"
ACCENT="#9e95c7"
ACCENT_DIM="#514d66"
SUCCES="#73c936"
TEXT="#e4e4ef"

set-option -g status-style bg=${SURFACE},fg=${TEXT}

set-option -g status-right " #S "
set-option -g status-right-style bg=${SURFACE},fg=${SUCCES},bold

set-option -g status-left ""
set-option -g status-left-style bg=${SURFACE},fg=${TEXT}

# Window status
set-option -g window-status-style bg=${SURFACE},fg=${ACCENT_DIM}
set-option -g window-status-format "#I"

set-option -g window-status-current-style bg=${SURFACE},fg=${ACCENT},bold
set-option -g window-status-current-format "#I"

# Panes
set-option -g pane-border-lines simple # single, double, heavy or simple
set-option -g pane-border-style fg=${ACCENT}
set-option -g pane-active-border-style fg=${ACCENT_DIM}
