# ~~~~~ GENERAL ~~~~~ #

# QoL
set -g escape-time 0
set -g repeat-time 1000
set -g history-limit 10000

# VI mode
set-window-option -g mode-keys vi

# Mouse mode
set-window-option -g mouse on

# Start window index at 1
set -g base-index 1

# Start pane index at 1
set -g pane-base-index 1

# Re-number windows when one is closed
set -g renumber-windows on


# ~~~~~ BINDINGS ~~~~~ #

# Re-set prefix
set-option -g prefix 'C-a'
bind-key 'C-a' send-prefix
unbind-key C-b

# Reload config
bind-key r source-file ~/.tmux.conf \; display "Fresh tmux config !"

# Use Alt-{h,j,k,l} keys to switch panes
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v

# ~~~~~ THEME ~~~~~ #

CANVAS="#101010"
SURFACE="#181818"
SURFACE_RAISED="#282828"
BORDER="#453d41"
BORDER_STRONG="#52494e"
TEXT="#e4e4ef"
TEXT_STRONG="#f4f4ff"
TEXT_MUTED="#95a99f"
ACCENT="#9e95c7"
ACCENT_DIM="#514d66"
SECONDARY="#96a6c8"
SECONDARY_SURFACE="#303540"
SUCCESS="#73c936"
WARNING="#ffdd33"
DANGER="#f43841"

# ~~~~~ STATUS BAR ~~~~~ #

set-option -g status-style "bg=${SURFACE},fg=${TEXT}"

set-option -g status-left ""
set-option -g status-left-style "bg=${SURFACE},fg=${TEXT}"

set-option -g status-right "#S"
set-option -g status-right-style "bg=${SURFACE},fg=${SUCCESS},bold"


# ~~~~~ WINDOWS ~~~~~ #

set-option -g window-status-style \
    "bg=${SURFACE},fg=${ACCENT_DIM}"
set-option -g window-status-format "￭" 

set-option -g window-status-current-style \
    "fg=#{?window_zoomed_flag,${WARNING},${SUCCESS}},bg=${SURFACE},bold"
set-option -g window-status-current-format "￭" 

set-option -g window-status-bell-style \
    "bg=${SURFACE},fg=${DANGER},bold"
set-option -g window-status-bell-format "￭" 


# ~~~~~ PANES ~~~~~ #

set-option -g pane-border-lines simple

# Inactive panes recede
set-option -g pane-border-style \
    "fg=${ACCENT_DIM}"

# Active pane gets the primary accent
set-option -g pane-active-border-style \
    "fg=${ACCENT}"
